/* Renders a <picture> with AVIF + WebP responsive sources generated by
   scripts/optimize-images.mjs. `src` is the base path without width/extension,
   e.g. "/images/parth-salon-interior". The original PNG is the final
   fallback so the image always resolves even if modern formats fail. */
const WIDTHS = [640, 960, 1440, 1526];

export function ResponsiveMedia({
  src,
  alt,
  width,
  height,
  sizes = "100vw",
  className = "",
  imgClassName = "",
  loading = "lazy",
  fetchPriority,
  style,
}: {
  src: string;
  alt: string;
  width: number;
  height: number;
  sizes?: string;
  className?: string;
  imgClassName?: string;
  loading?: "lazy" | "eager";
  fetchPriority?: "high" | "low" | "auto";
  style?: React.CSSProperties;
}) {
  const avif = WIDTHS.map((w) => `${src}-${w}.avif ${w}w`).join(", ");
  const webp = WIDTHS.map((w) => `${src}-${w}.webp ${w}w`).join(", ");
  return (
    <picture className={className}>
      <source type="image/avif" srcSet={avif} sizes={sizes} />
      <source type="image/webp" srcSet={webp} sizes={sizes} />
      <img
        src={`${src}.png`}
        alt={alt}
        width={width}
        height={height}
        loading={loading}
        decoding="async"
        fetchPriority={fetchPriority}
        className={imgClassName}
        style={style}
      />
    </picture>
  );
}
